# Generated by Django 5.1.6 on 2025-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
